feat: Add log_prob method to Model
stan-dev/pystan-next pull request #173
Opened 2020-12-01 17:12 UTC by mjcarter95

Added log_prob method to Model instances, allowing users to calculate
the log probability of a list of unconstrained parameters.

This feature is accompanied by a test: the log_prob method is validated
by comparing the output against the log probability (lp__) extracted
from a model fit.

Closes #40

2020-12-01 17:15 UTC, mjcarter95 commented
Ideally would convert `unconstrained_parameters` to a list (e.g. from numpy array) so they are JSON serializable. Should `_make_json_serializable` be updated to account for lists as well as dicts? Or should we add an additional function for lists?

2020-12-01 17:20 UTC, mjcarter95 commented on stan/model.py
> +            program_code (list[number]): A list of the unconstrained parameters.
`unconstrained_parameters (list[number]): A list of the unconstrained parameters.`

2020-12-01 18:01 UTC, ahartikainen commented
I think `payload` should go through `_make_json_serializable`?

It already supports lists and ndarrays?

2020-12-01 18:06 UTC, ahartikainen commented
Oh yes, I see what you mean. Should it have option for `if isinstance(item, dict)` --> recursion

Other way is to send it in with a dict (unconstrained params) -> unpack back

2020-12-01 19:33 UTC, mjcarter95 commented
I've gone for the second option for now, seems best to address the first as a separate issue?

2020-12-01 19:38 UTC, ahartikainen commented on stan/model.py
> +        assert all(not isinstance(value, np.ndarray) for value in unconstrained_parameters.values())
No need for the assert

2020-12-02 14:10 UTC, riddell-stan commented
FYI: Fully testing this requires a new release of `httpstan`. Making a new release is complicated by the fact that we use Travis CI for that. It may be the weekend before I have time to get to that.

Also, since this is the first PR from a new contributor, I think it makes sense for both me and @ahartikainen to review it. If nothing else, we can learn ways to make the process less painful. So, @ahartikainen , let me know when you're happy with the PR. I'll have a look at it then.

2020-12-02 16:19 UTC, mjcarter95 commented
@riddell-stan I tried to add yourself and Ari as reviewers after submitting the pull request, but there isn't an action on the RHS under "Reviewers: should I have done this before submitting?

On the new release of `httpstan`: given that we also discussed exposing `log_prob_grad`, `write_array`, and others in `httpstan`, should I first open new issues for these/satisfy them in `httpstan` before integrating here?

2020-12-02 17:42 UTC, riddell-stan commented
grad_log_prob is in PyStan 2. I don't think we need to have a discussion 
about porting that to PyStan 3. Just open PRs as you did with log_prob.

write_array needs discussion. Open an issue (here) and explain why it's 
needed.

On 12/2/20 11:19 AM, Matthew Carter wrote:
> @riddell-stan <https://github.com/riddell-stan> I tried to add yourself 
> and Ari as reviewers after submitting the pull request, but there isn't 
> an action on the RHS under "Reviewers: should I have done this before 
> submitting?
> 
> On the new release of |httpstan|: given that we also discussed exposing 
> |log_prob_grad|, |write_array|, and others in |httpstan|, should I first 
> open new issues for these/satisfy them in |httpstan| before integrating 
> here?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/stan-dev/pystan-next/pull/173#issuecomment-737336863>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AJQUBVRCADEAYS4GA4RVFXTSSZSKBANCNFSM4UJJTSUA>.
>

2020-12-03 22:33 UTC, mjcarter95 commented on tests/test_log_prob.py
> +    assert np.allclose(lp__, lp)
The test currently mirrors the test in `httpstan` (we only compare one value there), happy to compare all values if you think that would be better.

2020-12-07 14:57 UTC, ahartikainen reviewed
Looks good, I think there should be 1 test case where `adjust_transform=False`

2020-12-07 14:57 UTC, ahartikainen commented on tests/test_log_prob.py
> +    assert np.allclose(lp__, lp)
This is fine

2020-12-07 14:57 UTC, ahartikainen commented on tests/test_log_prob.py
> +    lp = posterior.log_prob(unconstrained_parameters=[y])
This tests case when `adjust_transform=True`, which is correct.

I think we should also add one test where `adjust_transform=False`

2020-12-10 21:44 UTC, mjcarter95 commented on tests/test_log_prob.py
> +    lp = posterior.log_prob(unconstrained_parameters=[y])
Reading over the documentation, I think that we should see Stan's value of `lp__` when setting `adjust_transform=False`? With this in mind, I'm not sure why we see the same values when `adjust_transform=True`: is this just down to the simplicity of the model? If so, should the model be modified to make this different behaviour apparent?

2020-12-11 07:26 UTC, ahartikainen commented on tests/test_log_prob.py
> +    lp = posterior.log_prob(unconstrained_parameters=[y])
yes, when you add restriction (e.g. `real<lower=0> y;` you can see the difference between `adjust_transform=True` and `adjust_transform=False`

2020-12-13 15:50 UTC, riddell-stan commented
httpstan 4.1.0 is on PyPI. We still need to get GitHub Actions working here though. Once GitHub Actions are working, we can rebase this and test it properly.

2020-12-13 15:56 UTC, riddell-stan requested changes
Looks good. A few minor things to fix. I agree with @ahartikainen about an additional test being nice to have.

2020-12-13 15:56 UTC, riddell-stan commented on stan/model.py
> +    def log_prob(self, unconstrained_parameters, adjust_transform=True):
Adding types to the function arguments would be nice. It would also allow us to shorten the docstring (we wouldn't need to mention the types).

2020-12-13 15:56 UTC, riddell-stan commented on stan/model.py
> +            io = ConsoleIO()
I don't think we need messages here. The function is going to return immediately. (We have messages during the sampling operation because sampling often takes (much) more than 1 second.)

2020-12-14 15:31 UTC, mjcarter95 commented
Addressed @riddell-stan's requested changes in the latest commit. On adding the restriction - I think this would also require `unconstrain_pars`, which I haven't had chance to add to HTTPStan yet, hopefully will soon!

2020-12-16 11:21 UTC, riddell-stan commented on stan/model.py
> +            unconstrained_parameters: A sequuence of unconstrained parameters.
```suggestion
            unconstrained_parameters: A sequence of unconstrained parameters.
```

2020-12-16 11:27 UTC, riddell-stan requested changes
A few more minor nits.

Also, please rebase this on `main` so the tests will run. (The CI setup was just fixed.)

Thanks again for this. Glad to have this feature back in PyStan.

2020-12-16 11:27 UTC, riddell-stan commented on stan/model.py
> +            Number: The log probability of the unconstrained parameters.
Use a type annotation for the return value. Also, I the return value is going to be `float`, not `Number`, right?

2020-12-16 11:27 UTC, riddell-stan commented on stan/model.py
> +            io = ConsoleIO()
```suggestion
```
I think you may have forgotten to remove this line.

2020-12-16 11:27 UTC, riddell-stan commented on stan/model.py
> +            pass
```suggestion
        return asyncio.run(go())
```
Let's remove the KeyboardInterrupt guard. This function is going to return so fast that nobody is going to have time to hit Control-C.

2020-12-16 21:39 UTC, mjcarter95 commented
Hi @riddell-stan, addressed all the suggested changes (minus additional test) in the latest commit. I have a few questions regarding the `transform_inits` method and Windows support, would it be best to discuss these on the discourse? I'll start working on `grad_log_prob` and `write_array` in the meantime.

2020-12-17 11:48 UTC, mjcarter95 commented
I'm not sure why the mypy errors below are appearing when creating the payload 

```
httpstan/stan/model.py:255: error: Incompatible types in assignment (expression has type "List[float]", target has type "Dict[Any, Any]")
httpstan/stan/model.py:256: error: Incompatible types in assignment (expression has type "bool", target has type "Dict[Any, Any]")
```

Any ideas?

2020-12-18 13:31 UTC, riddell-stan commented
I'll have a closer look soon. I'm a bit busy over the next few days.

2020-12-18 14:39 UTC, mjcarter95 commented
The error in the previous comment is fixed. Only thing outstanding is adding an additional test, but I think we really need `transform_inits` to be exposed before testing on models with constraints.

2020-12-23 10:03 UTC, mjcarter95 commented
I'll submit PR's for `constrain_pars` and `unconstrain_pars` soon, following that I can add the additional test to `log_prob`.

2021-01-12 13:05 UTC, mjcarter95 commented
Hi @riddell-stan @ahartikainen:
I've added `unconstrain_pars` to `Model` but I don't think that the latest version of HTTPStan (that includes `transform_inits`) is available on pip, which is causing the test to fail (see https://github.com/mjcarter95/pystan-next/runs/1687978654).

2021-01-12 20:16 UTC, riddell-stan commented
Looks like I forgot to push the 4.2.0 tag to httpstan's repo (fixed). If everything is set up correctly, httpstan 4.2.0 should appear on PyPI this evening (after 8PM EST).

2021-01-12 20:19 UTC, riddell-stan commented on stan/model.py
> +        upar = _make_json_serializable(upar)
Same complaint as with the previous PR. We can trust the (advanced) user to read the docstring.

2021-01-14 17:15 UTC, mjcarter95 commented
Added additional test for `adjust_transform=True`, there's probably a way for me to combine the two "posterior" functions into a single function that's cleaner but I'm not too familiar with pytest and was met with errors. If you have any suggestions I can modify the test.

2021-01-14 18:04 UTC, mjcarter95 commented
Not sure why my local black module isn't picking up on these formatting errors. Hopefully fixed in latest push along with tidied up log prob test.

2021-01-14 19:55 UTC, riddell-stan commented on tests/test_log_prob.py
> +    lp = posterior.log_prob(unconstrained_parameters=[y])
Is `adjust_transform==False` being tested? Other than this, I don't see anything wrong.

2021-01-14 20:17 UTC, mjcarter95 commented on tests/test_log_prob.py
> +    lp = posterior.log_prob(unconstrained_parameters=[y])
Added a second function to `test_log_prob` to test this

```
@pytest.mark.parametrize("posterior", [restricted_program], indirect=True)
def test_log_prob_restricted(posterior):
    """Test log probability against sampled model with restriction."""
    fit = posterior.sample(num_chains=num_chains, num_samples=num_samples)
    y = fit["y"][0][0]
    y_unconstrained = posterior.unconstrain_pars({"y": y})
    lp__ = fit["lp__"][0][0]
    lp = posterior.log_prob(unconstrained_parameters=y_unconstrained, adjust_transform=True)
    assert np.allclose(lp__, lp)
```

2021-01-14 20:26 UTC, riddell-stan commented
Sorry if I'm being dense. Can you point me to the line where log_prob is tested with `adjust_transform` as False? The default call has the value as True, I think.

2021-01-14 21:34 UTC, mjcarter95 commented
Doh! It's me being dense. I've added an extra assertion to the constrained model test:

```
lp = posterior.log_prob(unconstrained_parameters=y_unconstrained, adjust_transform=False)
assert not np.allclose(lp__, lp)
```

Checking that once value isn't equal to another feels a bit clunky to me, but I'm not sure how else to validate `adjust_transform=False` case. Do you know how the adjustment is done inside Stan?

2021-01-14 23:54 UTC, riddell-stan commented
I haven't used the log_prob method.

It certainly would be better to verify the calculation directly (as it 
should be easy to do). If it's not in the cmdstan docs or language 
manual you might ask on the forum.

On 1/14/21 4:34 PM, Matthew Carter wrote:
> Doh! It's me being dense. I've added an extra assertion to the 
> constrained model test:
> 
> |lp = posterior.log_prob(unconstrained_parameters=y_unconstrained, 
> adjust_transform=False) assert not np.allclose(lp__, lp) |
> 
> Checking that once value isn't equal to another feels a bit clunky to 
> me, but I'm not sure how else to validate |adjust_transform=False| case. 
> Do you know how the adjustment is done inside Stan?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/stan-dev/pystan-next/pull/173#issuecomment-760490475>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AJQUBVRNXJL4QAQWKNS4S3TSZ5PN3ANCNFSM4UJJTSUA>.
>

2021-01-15 13:44 UTC, riddell-stan commented
@mjcarter95 see p. 68 of the reference manual for a calculation of the adjustment.

2021-01-17 13:05 UTC, mjcarter95 commented
Thank you for digging that out @riddell-stan. The compiled model calls `lb_constrain` from the Stan math library (see [here](https://github.com/stan-dev/math/blob/2cf4310702eec1b14a355d883e704af0b788abd8/stan/math/prim/fun/lb_constrain.hpp)) which increments the log probability by the unconstrained input. Modified the test to mimic this behaviour.

2021-01-17 14:50 UTC, riddell-stan approved these changes

2021-01-17 14:50 UTC, merged